psql:
    DriverName: postgres
    Host: localhost
    Port: 5432
    User: postgres
    Password: postgres
    DbName: ses
    TableName: bulls

DataBase:
    ConnStr: "postgres://postgres:postgres@localhost:5432/ses?sslmode=disabled"

server:
    Host: localhost
    Port: 8080
